tcpsocket:
  enable: false
  port: 8879

websocket:
  enable: true
  port: 8878

server:
  port: 8877
  id: 1

Spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1


jwt:
  accessToken:
    secret: txuan123  # 跟im-platfrom的secret必须一致

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: im-server-group

message:
  mq:
    type: rocketmq


distributed:
  cache:
    type: redis

heartbeat:
    count: 10